AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with Apache HTTP server

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cf6f2b898ac0b337 # Amazon Linux 2023 AMI in London region
      # KeyName: MyKeyPair # Replace with your key pair name
      # SecurityGroups:
      #   - MySecurityGroup # Replace with your security group name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          service httpd start
          chkconfig httpd on