##############################################
## Add Parameters
##############################################

AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with Apache HTTP server

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type (e.g., t2.micro, t2.small, etc.)

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-xxxxxxxxxxxxx # Replace with your desired Amazon Linux AMI ID
      KeyName: MyKeyPair # Replace with your key pair name
      SecurityGroups:
        - MySecurityGroup # Replace with your security group name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          service httpd start
          chkconfig httpd on


Outputs:
  PublicIp:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  PublicDnsName:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName